from typing import Callable  # noqa

### ALOHA fixed constants
DT = 0.02
JOINT_NAMES = [
    "waist",
    "shoulder",
    "elbow",
    "forearm_roll",
    "wrist_angle",
    "wrist_rotate",
]

# Left finger position limits (qpos[7]), right_finger = -1 * left_finger
MASTER_GRIPPER_POSITION_OPEN = (0.03202558308839798 + 0.03293491154909134) / 2.0
MASTER_GRIPPER_POSITION_CLOSE = (0.01871558278799057 + 0.018229320645332336) / 2.0
PUPPET_GRIPPER_POSITION_OPEN = 0.05800
PUPPET_GRIPPER_POSITION_CLOSE = 0.04400

PUPPET_GRIPPER_POSITION_OPEN_OLD = 0.05800
PUPPET_GRIPPER_POSITION_CLOSE_OLD = 0.01844

PUPPET_GRIPPER_POSITION_NEW_TO_OLD = (
    lambda x: (x - PUPPET_GRIPPER_POSITION_CLOSE)
    * (PUPPET_GRIPPER_POSITION_OPEN_OLD - PUPPET_GRIPPER_POSITION_CLOSE_OLD)
    / (PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE)
    + PUPPET_GRIPPER_POSITION_CLOSE_OLD
)

START_ARM_POSE = [
    0,
    -0.96,
    1.16,
    0,
    -0.3,
    0,
    PUPPET_GRIPPER_POSITION_CLOSE,
    -PUPPET_GRIPPER_POSITION_CLOSE,
    0,
    -0.96,
    1.16,
    0,
    -0.3,
    0,
    PUPPET_GRIPPER_POSITION_CLOSE,
    -PUPPET_GRIPPER_POSITION_CLOSE,
]

START_ARM_POSE_SINGLE = [
    0,
    -0.96,
    1.16,
    0,
    -0.3,
    0,
    PUPPET_GRIPPER_POSITION_CLOSE,
    -PUPPET_GRIPPER_POSITION_CLOSE,
]

START_ARM_POSE_SINGLE_SWEEP = [
    0,
    -0.96,
    1.16,
    0,
    -0.3,
    0,
    PUPPET_GRIPPER_POSITION_CLOSE,
    -PUPPET_GRIPPER_POSITION_CLOSE,
]

ARM_OFFSET = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

START_EE_POSE = [
    2.56418115e-01,
    -5.50126845e-04,
    2.95703636e-01,
    6.88682872e-04,
    -3.83402967e-02,
    -1.18223866e-03,
    9.99263804e-01,
    -0.3,
]

# Gripper joint limits (qpos[6])
MASTER_GRIPPER_JOINT_OPEN = (0.803805947303772 + 0.8651651740074158) / 2.0
MASTER_GRIPPER_JOINT_CLOSE = (-0.09357283264398575 + -0.05675728991627693) / 2.0
PUPPET_GRIPPER_JOINT_OPEN = (1.6751071214675903 + 1.6950488090515137) / 2.0
PUPPET_GRIPPER_JOINT_CLOSE = 0.4

MASTER_GRIPPER_JOINT_OPEN_OLD = 0.3083
MASTER_GRIPPER_JOINT_CLOSE_OLD = -0.6842
PUPPET_GRIPPER_JOINT_OPEN_OLD = 1.4910
PUPPET_GRIPPER_JOINT_CLOSE_OLD = -0.6213

############################ Helper functions ############################

MASTER_GRIPPER_POSITION_NORMALIZE_FN = lambda x: (x - MASTER_GRIPPER_POSITION_CLOSE) / (
    MASTER_GRIPPER_POSITION_OPEN - MASTER_GRIPPER_POSITION_CLOSE
)  # type: Callable[[float], float]
PUPPET_GRIPPER_POSITION_NORMALIZE_FN = lambda x: (x - PUPPET_GRIPPER_POSITION_CLOSE) / (
    PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE
)  # type: Callable[[float], float]
MASTER_GRIPPER_POSITION_UNNORMALIZE_FN = (
    lambda x: x * (MASTER_GRIPPER_POSITION_OPEN - MASTER_GRIPPER_POSITION_CLOSE)
    + MASTER_GRIPPER_POSITION_CLOSE
)  # type: Callable[[float], float]
PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN = (
    lambda x: x * (PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE)
    + PUPPET_GRIPPER_POSITION_CLOSE
)  # type: Callable[[float], float]
MASTER2PUPPET_POSITION_FN = lambda x: PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN(
    MASTER_GRIPPER_POSITION_NORMALIZE_FN(x)
)  # type: Callable[[float], float]

MASTER_GRIPPER_JOINT_NORMALIZE_FN = lambda x: (x - MASTER_GRIPPER_JOINT_CLOSE) / (
    MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE
)  # type: Callable[[float], float]
PUPPET_GRIPPER_JOINT_NORMALIZE_FN = lambda x: (x - PUPPET_GRIPPER_JOINT_CLOSE) / (
    PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE
)  # type: Callable[[float], float]
MASTER_GRIPPER_JOINT_UNNORMALIZE_FN = (
    lambda x: x * (MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE)
    + MASTER_GRIPPER_JOINT_CLOSE
)  # type: Callable[[float], float]
PUPPET_GRIPPER_JOINT_UNNORMALIZE_FN = (
    lambda x: x * (PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE)
    + PUPPET_GRIPPER_JOINT_CLOSE
)  # type: Callable[[float], float]
PUPPET_GRIPPER_JOINT_UNNORMALIZE_FN_OLD = (
    lambda x: x * (PUPPET_GRIPPER_JOINT_OPEN_OLD - PUPPET_GRIPPER_JOINT_CLOSE_OLD)
    + PUPPET_GRIPPER_JOINT_CLOSE_OLD
)  # type: Callable[[float], float]
PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN_OLD = (
    lambda x: x * (PUPPET_GRIPPER_POSITION_OPEN_OLD - PUPPET_GRIPPER_POSITION_CLOSE_OLD)
    + PUPPET_GRIPPER_POSITION_CLOSE_OLD
)  # type: Callable[[float], float]
PUPPET_GRIPPER_JOINT_NORMALIZE_FN_OLD = lambda x: (
    x - PUPPET_GRIPPER_JOINT_CLOSE_OLD
) / (
    PUPPET_GRIPPER_JOINT_OPEN_OLD - PUPPET_GRIPPER_JOINT_CLOSE_OLD
)  # type: Callable[[float], float]
PUPPET_GRIPPER_POSITION_NORMALIZE_FN_OLD = lambda x: (
    x - PUPPET_GRIPPER_POSITION_CLOSE_OLD
) / (
    PUPPET_GRIPPER_POSITION_OPEN_OLD - PUPPET_GRIPPER_POSITION_CLOSE_OLD
)  # type: Callable[[float], float]
MASTER2PUPPET_JOINT_FN = lambda x: PUPPET_GRIPPER_JOINT_UNNORMALIZE_FN(
    MASTER_GRIPPER_JOINT_NORMALIZE_FN(x)
)  # type: Callable[[float], float]
MASTER2PUPPET_JOINT_FN_OLD = lambda x: PUPPET_GRIPPER_JOINT_UNNORMALIZE_FN_OLD(
    MASTER_GRIPPER_JOINT_NORMALIZE_FN(x)
)  # type: Callable[[float], float]
MASTER_GRIPPER_VELOCITY_NORMALIZE_FN = lambda x: x / (
    MASTER_GRIPPER_POSITION_OPEN - MASTER_GRIPPER_POSITION_CLOSE
)  # type: Callable[[float], float]
PUPPET_GRIPPER_VELOCITY_NORMALIZE_FN = lambda x: x / (
    PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE
)  # type: Callable[[float], float]

MASTER_POS2JOINT = (
    lambda x: MASTER_GRIPPER_POSITION_NORMALIZE_FN(x)
    * (MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE)
    + MASTER_GRIPPER_JOINT_CLOSE
)  # type: Callable[[float], float]
MASTER_JOINT2POS = lambda x: MASTER_GRIPPER_POSITION_UNNORMALIZE_FN(
    (x - MASTER_GRIPPER_JOINT_CLOSE)
    / (MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE)
)  # type: Callable[[float], float]
PUPPET_POS2JOINT = (
    lambda x: PUPPET_GRIPPER_POSITION_NORMALIZE_FN(x)
    * (PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE)
    + PUPPET_GRIPPER_JOINT_CLOSE
)  # type: Callable[[float], float]
PUPPET_JOINT2POS = lambda x: PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN(
    (x - PUPPET_GRIPPER_JOINT_CLOSE)
    / (PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE)
)  # type: Callable[[float], float]

MASTER_GRIPPER_JOINT_MID = (MASTER_GRIPPER_JOINT_OPEN + MASTER_GRIPPER_JOINT_CLOSE) / 2
