dataset_path: ../dataset/manifeel/data
models_save_dir: saved_checkpoint_manifeel
output_dir: saved_checkpoint_manifeel

# hyperparams
num_epochs: 300
num_train_demos: 500
# obs_horizon sets num_steps_conditioning in the model.
# pred_horizon = obs_horizon + 1 => seq_length = 1 (single-step warmup).
obs_horizon: 4
pred_horizon: 5
action_horizon: 5
batch_size: 16
resize_scale: 96
wandb: false
