num_diffusion_iters: 100
pred_horizon: 16
obs_horizon: 2
action_horizon: 8
resize_scale: 96
wandb: false
output_dir: gpc_rank_evaluation_output
max_steps: 300
num_episodes: 1
start_number_test: 0
save_video: false

policy_checkpoint: ./all_checkpoints/action_policy_checkpoint/checkpoint_epoch_300
world_model_checkpoint: ./all_checkpoints/world_model_checkpoint/phase_two_checkpoint/denoiser.pth
reward_predictor_xy_checkpoint: ./all_checkpoints/reward_checkpoint/reward_predictor_xy.pth
reward_predictor_angle_checkpoint: ./all_checkpoints/reward_checkpoint/reward_predictor_angle.pth
